### ISSUE TITLE
Where did MalariaHostAtlas groupings end up in AnnData transfer?

### ISSUE THREAD

**Issue by haessar** [iii-cell-atlas/MalariaHostAtlas#1]
For [MalariaHostAtlas](http://cellatlas.mvls.gla.ac.uk/MalariaHostAtlas/), the UMAP contains various cluster markers, set in the Seurat object during pre-processing ("Early Rings", "Mid Rings", etc).

When performing a crude Seurat > AnnData conversion and loading this dataset into cellxgene, these markers appear to have disappeared: http://cellatlas-dev.mvls.gla.ac.uk/public/view/out.h5ad/

Tasks: 
1.  Find out exactly how these markers were being set for the Seurat object; whether they were set in the .RDS data at all or applied in custom code later on. Worth tracing through app.R and tcell_libs_raw_dash.R
 in the [MalariaHostAtlas source code](https://github.com/iii-cell-atlas/MalariaHostAtlas).
2.  Determine whether it's possible to add them to the AnnData file so they are visible in the cellxgene UMAP at launch.

**Comment by haessar** [comment]
You can see the labels in cellxgene by clicking on any of the "Use as colour scale" buttons for any grouping:
![image](https://user-images.githubusercontent.com/11962461/157877134-8db85fc3-9748-41c3-9bfd-57d220323894.png)
And then this button in top right:
![image](https://user-images.githubusercontent.com/11962461/157877324-7b5ad1ff-f1ee-4311-98fd-3bb4dbb8ad10.png)

**Comment by EdwardAgboraw** [comment]
1. The Cell Cluster labels are stored in the "Stages" meta-data variable of the Seurat object . From what I can tell this meta-data variable already exists in the Seurat object when its loaded into "tcell_libs_raw_dash.R", and then the function starting at line 150 more firmly associates it with the clusters. 

2. The "Stages" metadata variable is stored as a Factor in the Seurat object. Seurat seems to treat Factors as integers (the "levels" of the factor) associated with labels (what the levels are called). So when a Seurat object is converted to an AnnData object, only the integer levels of the factor variables are transferred - the actual labels are abandoned.

However, if you specifically convert the factor into a character vector In R before the Seurat-AnnData conversion 
(e.g. TCellSeurat@meta.data$Stages = as.character(TCellSeurat@meta.data$Stages)), then the labels are preserved and show up in CELLXGENE.

**Comment by EdwardAgboraw** [comment]
![Task1Success](https://user-images.githubusercontent.com/18103832/158359930-ca07b573-48c1-4ae7-ab77-4daf39691526.jpg)

**Comment by haessar** [comment]
Good detective work, so now we can see the labels applied also on the full UMAP:

![image](https://user-images.githubusercontent.com/11962461/158421557-f1c17eb8-0faa-47fd-8ed3-b41299d6c2a5.png)

Added the updated dataset to the dev server here: http://cellatlas-dev.mvls.gla.ac.uk/public/view/out1.h5ad/
